cart/urls.py
from django.urls import path,include

from . import views
from .cart_context import delete_cart
from rest_framework.routers import DefaultRouter
from .api_view import CartItemViewSet

router = DefaultRouter()
router.register(r'api/cart-items', CartItemViewSet, basename='cart-item')

urlpatterns = [
    path('' , views.cart , name='cart'),
    path('add_to_cart/<str:product_id>/' , views.add_to_cart , name='add_to_cart'),
    path('decrement_cart/<str:product_id>/<str:cart_item_id>/' , views.decrement_cart , name='decrement_cart'),
    path('delete_cart/<str:product_id>/<str:cart_item_id>/' , delete_cart , name='delete_cart'),
    path('checkout/' , views.checkout , name='checkout'),

    # API
    path('', include(router.urls)),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from settings.views import  custom_404_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('settings.urls') ),
    path('products/' , include('store.urls')),
    path('accounts/' , include('accounts.urls')),
    path('cart/' , include('cart.urls')),
    path('order/' , include('order.urls')),
    path('categories/' , include('category.urls')),
    path('dashboard/' , include('dashboard.urls')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path

from settings.api_view import ContactUsView, NewsletterView
from . import views

urlpatterns = [
    path('' , views.home , name='home'),
    
    # API
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('newsletter/', NewsletterView.as_view(), name='newsletter'),
    path('last-six-products/', views.LastSixProductsView.as_view(), name='last_six_products'),
]

category/models.py
from django.db import models
import uuid

from django.urls import reverse

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(null=True,blank=True,upload_to='category-image/')

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['name']  # Categories will be ordered alphabetically by name.

    def __str__(self):
        return self.name
    
    # Add a method to count the products in this category
    def product_count(self):
        return self.subcategories.aggregate(count=models.Count('product_subcategory'))['count'] or 0

class Subcategory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(null=True,blank=True,upload_to='subcategory-image/')

    class Meta:
        verbose_name = "Subcategory"
        verbose_name_plural = "Subcategories"
        ordering = ['name']  # Subcategories will be ordered alphabetically by name.

    def __str__(self):
        return f"{self.category.name} - {self.name}"
    
    def get_url(self):
        return reverse('products_by_subcategory',args=[self.id])
    
    # Add a method to count the products in this subcategory
    def product_count(self):
        return self.product_subcategory.count()

settings/models.py
from django.db import models

# Create your models here.

class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)
    is_solved = models.BooleanField(default=False)  # Corrected spelling
    solved_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Message from {self.name} ({self.email})"
    

class Newsletter(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

settings/views.py
from django.shortcuts import render
from rest_framework.generics import ListAPIView
from store.models import Product
from store.serializers import ProductSerializer
# Create your views here.

def home(request):

    products = Product.objects.all().order_by('-views')
    context = {
        'products':products
    }
    return render(request,'home.html',context)

def custom_404_view(request, exception=None):
    return render(request, '404.html', {}, status=404)

class LastSixProductsView(ListAPIView):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.order_by('-id')[:6]

settings/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Home
{% endblock title %}
{% block body %}
<div class="hero-slider">
  <div class="slider-item th-fullpage hero-area" style="background-image: url({% static 'images/slider/slider-1.jpg' %});">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 text-center">
          <p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">PRODUCTS</p>
          <h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">The beauty of nature <br> is hidden in details.</h1>
          <a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="{% url 'product_list' %}">Shop Now</a>
        </div>
      </div>
    </div>
  </div>
  <div class="slider-item th-fullpage hero-area" style="background-image: url({% static 'images/slider/slider-3.jpg' %});">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 text-left">
          <p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">PRODUCTS</p>
          <h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">The beauty of nature <br> is hidden in details.</h1>
          <a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="{% url 'product_list' %}">Shop Now</a>
        </div>
      </div>
    </div>
  </div>
  <div class="slider-item th-fullpage hero-area" style="background-image: url({% static 'images/slider/slider-2.jpg' %});">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 text-right">
          <p data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1">PRODUCTS</p>
          <h1 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".5">The beauty of nature <br> is hidden in details.</h1>
          <a data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".8" class="btn" href="{% url 'product_list' %}">Shop Now</a>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="product-category section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title text-center">
                    <h2>Product Category</h2>
                </div>
            </div>
            {% for category in categories_nav %}
            <div class="col-md-6">
                <div class="category-box">
                    <a href="{% url 'products_by_category' category.id %}">
                        <img src="{% if category.image %}{{ category.image.url }}{% endif %}" alt="{{ category.name }}" />
                        <div class="content">
                            <h3>{{ category.name }}</h3>
                            <p>{{ category.product_count }} products</p>
                        </div>
                    </a>	
                </div>
                {% for subcategory in category.subcategory_set.all %}
                <div class="category-box">
                    <a href="{{subcategory.get_url}}">
                        <img src="{{ subcategory.image.url }}" alt="{{ subcategory.name }}" />
                        <div class="content">
                            <h3>{{ subcategory.name }}</h3>
                            <p>{{ subcategory.description }}</p>
                        </div>
                    </a>	
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</section>


<section class="products section bg-gray">
	<div class="container">
		<div class="row">
			<div class="title text-center">
				<h2>Trendy Products</h2>
			</div>
		</div>
		<div class="row">

            {% for product in products %}
			
			<div class="col-md-3">
				<div class="product-item">
					<div class="product-thumb">
                        {% if product.on_sale %}
						<span class="bage">Sale</span>
                        {% endif %}
						<img class="img-responsive" src="{{product.image.url}}" alt="product-img" />
						<div class="preview-meta">
							<ul>
								<li>
									<span  data-toggle="modal" data-target="#product-modal-{{ product.id }}">
										<i class="tf-ion-ios-search-strong"></i>
									</span>
								</li>
								<li>
			                        {% if request.user in product.like.all %}
                                            <a href="{% url 'add_to_favourit' product.id%}"><i class="fa-solid fa-heart"></i></a>
                                            {% else %}
                                            <a href="{% url 'add_to_favourit' product.id%}"><i class="fa-regular fa-heart"></i></a>
                                            {% endif %}
								</li>
								<li>
									<a href="{% url 'add_to_cart' product.id%}"><i class="tf-ion-android-cart"></i></a>
								</li>
							</ul>
                      	</div>
					</div>
					<div class="product-content">
						<h4><a href="{% url 'product_details' product.id %}">{{product.name}}</a></h4>
						<p class="price">${{product.price}}</p>
					</div>
				</div>
			</div>
            <!-- Modal -->
		<div class="modal product-modal fade" id="product-modal-{{ product.id }}">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<i class="tf-ion-close"></i>
			</button>
		  	<div class="modal-dialog " role="document">
		    	<div class="modal-content">
			      	<div class="modal-body">
			        	<div class="row">
			        		<div class="col-md-8 col-sm-6 col-xs-12">
			        			<div class="modal-image">
				        			<img class="img-responsive" src="{{product.image.url}}" alt="product-img" />
			        			</div>
			        		</div>
			        		<div class="col-md-4 col-sm-6 col-xs-12">
			        			<div class="product-short-details">
			        				<h2 class="product-title">{{product.name}}</h2>
			        				<p class="product-price">${{product.price}}</p>
			        				<p class="product-short-description">
			        					{{product.description}}
			        				</p>
			        				<a href="{% url 'add_to_cart' product.id%}" class="btn btn-main">Add To Cart</a>
			        				<a href="{% url 'product_details' product.id %}" class="btn btn-transparent">View Product Details</a>
			        			</div>
			        		</div>
			        	</div>
			        </div>
		    	</div>
		  	</div>
		</div><!-- /.modal -->
			{% endfor %}

		</div>
	</div>
</section>


<!--
Start Call To Action
==================================== -->
<section class="call-to-action bg-gray section">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="title">
					<h2>SUBSCRIBE TO NEWSLETTER</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, <br> facilis numquam impedit ut sequi. Minus facilis vitae excepturi sit laboriosam.</p>
				</div>
				<div class="col-lg-6 col-md-offset-3">
				    <div class="input-group subscription-form">
				      <input type="text" class="form-control" placeholder="Enter Your Email Address">
				      <span class="input-group-btn">
				        <button class="btn btn-main" type="button">Subscribe Now!</button>
				      </span>
				    </div><!-- /input-group -->
			  </div><!-- /.col-lg-6 -->

			</div>
		</div> 		<!-- End row -->
	</div>   	<!-- End container -->
</section>   <!-- End section -->

{% endblock body %}